config/routes.rb
Rails.application.routes.draw do
   devise_for :customers, controllers: {
   sessions:      'customers/sessions',
   passwords:     'customers/passwords',
   registrations: 'customers/registrations'
  }
namespace :customers do

          resources :bookmarks, only: [:index, :create, :update, :destroy]
end
  scope module: 'customers' do
    root 'items#top'
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'

      resources :bookmarks, only: [:index, :create, :update, :destroy]
       resources :customers, only: [:show, :edit, :update] do
       #get :cart_items, on: :collection
       resources :customers, only: [:show] do 
           
           resources :items, only: %i[index new create show edit destroy update], shallow: true do
  get :bookmarks, on: :collection
  resource :bookmarks, only: %i[create destroy]
end
  end
   end
   end
   
 
   

   resources :bookmarks, only: [:create, :destroy]
 

  namespace :customers do
      resources :items, only: [:new, :create, :index, :show, :destroy] do
          
  
    resources :post_comments, only: [:create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
  end
   
   resources :genres, only: [:show]
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
 
   get 'customers/edit' => 'customers#edit'
   patch 'update' => 'customers#update'
   get 'quit' => 'customers#quit'
   get 'orders/about' => 'orders#about', as: 'orders_about'
   get 'orders/complete' => 'orders#complete'
   resources :orders, only: [:create, :new, :index, :show]
   resources :bookmarks, only: [:index, :create, :update, :destroy]

 
  end

  # adminルーティング
  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  namespace :admins do
   root :to => 'top#top'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
    before_action :authenticate_admin!
  
  def index
    @customers = Customer.all
    
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admins_customer_path(@customer)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      edit_admins_customer_path(@customer)
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number, :email, :is_customer_status)
  end
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
    before_action :authenticate_admin!,only: [:create,:edit,:update,:index, :show, :new]

  def show
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
  end

  def new
    @items = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admins_item_path(@item)
    else
      flash[:genre_created_error] = "ジャンル名を入力してください"
    redirect_to new_admins_item_path
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_items_path(@item)
      flash[:notice_update] = "ジャンル情報を更新しました！"
    else
      redirect_to edit_admins_item_path(@item)
    end
  end

  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :description, :price_without_tax, :image, :is_sales_status)
  end
end

app/controllers/customers/bookmarks_controller.rb
class Customers::BookmarksController < ApplicationController
     before_action :authenticate_customer!
    
  def index
    @bookmarks = current_customer.bookmarks
    customer = current_customer
    @customer_bookmarks = customer.bookmarks
    #@item = Item.find(params[:id])
    #@items = Item.all
    
  end
    
  def create
      @bookmark = Bookmark.new()
      @bookmark.customer_id = current_customer.id
      @bookmark.item_id = params[:item_id]
    @item = Item.find(params[:item_id])
    
     if @bookmark.save
           flash[:notice] = "#{@bookmark.item.name}をお気に入りに追加しました。"
           redirect_to item_path(params[:item_id])
     else
      
            redirect_to item_path(params[:item_id])
     end
    #current_customer.bookmark(item)
    #redirect_back fallback_location: root_path, success: t('defaults.message.bookmark')
  end

  def destroy
      @bookmark = Bookmark.find(params[:id])
      @bookmark.destroy
    #@item = current_customer.bookmarks.find(params[:id]).item
    #current_customer.unbookmark(item)
    #redirect_back fallback_location: root_path, success: t('defaults.message.unbookmark')
  end
  
  private
  def bookmark_params
    params.require(:bookmark).permit(:item_id, :image)
  end
  
  def item_params
    params.require(:item).permit(:image)
  end
 
end

app/controllers/customers/cart_items_controller.rb
class Customers::CartItemsController < ApplicationController
     before_action :authenticate_customer!

 
    def index
        @items = Item.all

    end


    def create
        # @cart_item = current_customer.cart_items.build(item_id: params[:item_id])
        @cart_item = CartItem.new()
        @item = Item.find(params[:item_id])
            
        #@cart_item = CartItem.create(customer_id: current_customer.id, item_id: @item.id)
        @cart_item.customer_id = current_customer.id
        @cart_item.item_id = params[:item_id]
        # byebug

        if @cart_item.save
           flash[:notice] = "#{@cart_item.item.name}をお気に入りに追加しました。"
           redirect_to item_path(params[:item_id])
        else
            flash[:alert] = "個数を選択してください"
            redirect_to item_path(params[:item_id])
        end
    end

    # 削除や個数を変更した際、カート商品を再計算する
    def update
        @cart_item = CartItem.find(params[:id])
        #@cart.units += cart_params[:units].to_i
        @cart_item.update(cart_item_params)
        redirect_to customers_cart_items_path
    end

    # カート商品を一つのみ削除
    def destroy
     @cart_item = CartItem.find_by(item_id: params[:id], customer_id: current_customer.id)
        @cart_item.destroy
        flash.now[:alert] = "#{@cart_item.item.name}を削除しました"
        redirect_to item_path(params[:id])
    end


 

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
     before_action :authenticate_customer!

    # マイページへのアクション
    def show
        @customer = current_customer
        
    end

    # 登録情報編集へのアクション
    def edit
        @customer = current_customer
    end

    # 登録情報の編集を保存するアクション
    def update
        @customer = current_customer
        if @customer.update(customer_params)
           flash[:success] = "登録情報を変更しました。"
           redirect_to customers_show_path
        else
            render 'edit'
        end
    end

    # 登録情報編集画面から退会ページを表示するアクション
    def quit

    end

    # 退会アクション
    def withdraw
        @customer = current_customer
        
        # is_customer_statusカラムにフラグを立てる(default→false(有効状態)をtrue(無効状態)にする）
        @customer.update(is_customer_status: true)
        # ログアウトさせる
        reset_session

        flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
        redirect_to root_path
    end

    private
        def customer_params
            params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :phone_number, :is_customer_status)
        end
end

app/controllers/customers/favorites_controller.rb
class Customers::FavoritesController < ApplicationController
    def create
        post_comment = PostComment.find(params[:post_comment_id])
        favorite = current_customer.favorites.new(post_comment_id: post_comment.id)
        favorite.save
        redirect_to items_path
    end
    
    def destroy
        post_comment = PostComment.find(params[:post_comment_id])
        favorite = current_customer.favorites.find_by(post_comment_id: post_comment.id)
        favorite.destroy
        redirect_to items_path
    end
end

app/controllers/customers/genres_controller.rb
class Customers::GenresController < ApplicationController
     def show
    @genre = Genre.find(params[:id])
    @items = Item.where(genre_id: @genre.id).page(params[:page]).per(8)
    @genres = Genre.all
     end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
    
 def top
  @genres = Genre.all
  @items = Item.all
 end



#def bookmarks
#@bookmarks_items = current_customer.bookmark_items.includes(:customer).order(created_at: :desc)
#end

 def index
  @genres = Genre.all
  
  @items = Item.all
  @items_all = Item.all
  
  #検索オブジェクト
  @search = Item.ransack(params[:q])
  #検索結果
  @items = @search.result
 end

 
 def show
  @item = Item.find(params[:id])
  @bookmark = Bookmark.new
  @genres = Genre.all
  @post_comment = PostComment.new
 end

 def about
    
 end


  private
  def item_params
    params.require(:item).permit(:image)
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController
    
    before_action :authenticate_customer!

	def about
		@order = Order.new
		@customer = current_customer
		@addresses = ShippingAddress.where(customer_id: current_customer.id)
	end

	def create
		customer = current_customer

		
		session[:order] = Order.new

		cart_items = current_customer.cart_items

		
		sum = 0
		cart_items.each do |cart_item|
			sum += (cart_item.item.price_without_tax * 1.1).floor * cart_item.quantity
		end

		session[:order][:postage] = 800
		session[:order][:total_payment] = sum + session[:order][:postage]
		session[:order][:order_status] = 0
		session[:order][:customer_id] = current_customer.id
		
		session[:order][:payment_method] = params[:method].to_i

		
		destination = params[:a_method].to_i

		
		if destination == 0

			session[:order][:post_code] = customer.postal_code
			session[:order][:address] = customer.address
			session[:order][:name] = customer.last_name + customer.first_name

		
		elsif destination == 1

			address = ShippingAddress.find(params[:shipping_address_for_order])
			session[:order][:post_code] = address.postal_code
			session[:order][:address] = address.address
			session[:order][:name] = address.name 

		
		elsif destination == 2

			session[:new_address] = 2
			session[:order][:post_code] = params[:post_code]
			session[:order][:address] = params[:address]
			session[:order][:name] = params[:name]

		end

		
		if session[:order][:post_code].presence && session[:order][:address].presence && session[:order][:name].presence
			redirect_to new_customers_order_path
		else
			redirect_to customers_orders_about_path
		end

	end


	def new
		@cart_items = current_customer.cart_items
	end



	def complete
		order = Order.new(session[:order])
		order.save

		if session[:new_address]
			shipping_address = current_customer.shipping_addresses.new
			shipping_address.postal_code = order.post_code
			shipping_address.address = order.address
			shipping_address.name = order.name
			shipping_address.save
			session[:new_address] = nil
		end


		cart_items = current_customer.cart_items
		cart_items.each do |cart_item|
			order_detail = OrderDetail.new
			order_detail.order_id = order.id
			order_detail.item_id = cart_item.item.id
			order_detail.quantity = cart_item.quantity
			order_detail.making_status = 0
			order_detail.price = (cart_item.item.price_without_tax * 1.1).floor
			order_detail.save
		end


		cart_items.destroy_all
	end

	def index
		@orders = current_customer.orders
	end

	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
	end

end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/post_comments_controller.rb
class Customers::PostCommentsController < ApplicationController
  def create
    @item = Item.find(params[:item_id])
    comment = current_customer.post_comments.new(post_comment_params)
    comment.item_id = @item.id
    comment.save
    redirect_to items_path
  end

 def destroy
    PostComment.find(params[:id]).destroy
    redirect_to items_path
 end
  
  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/views/customers/items/about.html.erb
<div class="row">
    <div class="col-xs-6">
    </div>
    <div class="col-xs-6">
    <div>
       Comics
    </div>
    </div>
</div>

app/views/customers/items/index.html.erb
<div class="pull-right" style="margin-bottome: 10px;">
	<%= search_form_for(@search, url:items_path) do |f| %>
		<%= f.label :name, "書籍名" %>
		<%= f.search_field :name_cont %>
		<%= f.submit %>
	<% end %>
</div>


<div class="row">
	<div class="col-xs-2">

	</div>

  <h2 style="margin: 20px 0;">書籍一覧(全<%= @items_all.count %>件)</h2>
	<div class="col-xs-9 col-xs-offset-1">
		<div class="product-card-content">


		<% @items.each do |item| %>
		<div class="col-xs-3" style="padding-right: 0px; padding-left: 0px; margin: 10px 0;">
			<%= link_to item_path(item.id) ,style: "color: black;", data: {"turbolinks" => false} do %>
		 <%= image_tag item.image, size: "50x50" %>
				<%= item.name %>
		<p><%= link_to "#{item.post_comments.count} コメント", item_path(item.id) %></p>
			<% end %>
		</div>
		<% end %>
		</div>
	</div>
	<div style="text-align: center;"></div>
</div>

app/views/customers/items/show.html.erb
<div class="row">
	<div class="col-xs-2">
	
	</div>

	<br>
	<div class="col-xs-5">
		<p class="item-content1"><%= image_tag @item.image, size: "50x50", format: 'jpeg',fallback: "no_image.jpg", size:'380x300' %></p>
	</div>



	    <div class="col-xs-5">
		      <h3><%= @item.name %></h3>
	      	<p><%= @item.description %></p>
	    </div>
	    
</div>

<div class="row">
	<div class="col-xs-2">
	</div>
	<div class="col-xs-5">
	</div>
	 <% if Bookmark.find_by(item_id: @item.id, customer_id: current_customer.id) %>
	 		<div class="col-xs-5">
		  <p>
		  <%= link_to "お気に入り解除", customers_bookmarks_path(item_id: @item), method: :delete %>
		  </p>
		  </div>
    <% else %>
	<%= form_for(@bookmark , url: customers_bookmarks_path(item_id: @item), method: :post) do |form| %>
		<div class="col-xs-5">
		  <p><%= form.submit "お気に入り登録", class:"btn btn-primary" %></p>
		</div>
	<% end %>
	<% end %>
</div>
	
	<div>
  <p>コメント件数：<%= @item.post_comments.count %></p>
  <% @item.post_comments.each do |post_comment| %>
    <p><%#= image_tag post_comment.user.get_profile_image(100,100) %></p>
    <%= post_comment.customer.last_name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
    <% if post_comment.customer == current_customer %>
      <%= link_to "削除", customers_item_post_comment_path(post_comment.item, post_comment), method: :delete %>
    <% end %>
    
    <% if post_comment.favorited_by?(current_customer) %>
    <p>
      <%= link_to customers_item_post_comment_favorites_path(@item,post_comment), method: :delete do %>
        ♥<%= post_comment.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to customers_item_post_comment_favorites_path(@item,post_comment), method: :post do %>
        ♡<%= post_comment.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
  <% end %>
</div>
<div>
  <%= form_with model: [@item, @post_comment] ,url:  customers_item_post_comments_path(@item) ,method: :post do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに（ネタバレはお控えください）" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>
</div>

app/views/customers/items/top.html.erb
      <main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>ようこそ、 <i class="fas fa-book" ></i><strong>Comicsへ</strong>  !!</h1>
      <p>この  <i class="fas fa-book"></i><strong>Comicsは</strong>、 </p>
      <p>漫画のレビューサイトになります。</p>
      <p> 会員でない方も漫画の検索はできますが、</p>
      <p>お気に入り登録等には会員登録が必要になります。</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/customers/sign_in">ログイン</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/customers/sign_up">新規登録</a>
        </div>
      </div>
    </div>
  </div>
</div>
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h3 class="recommended-items" style="font-family: HiraMinPro-W6; color: #000000;">オススメコミック</h3>

        <!-- 商品を4つ表示するようにする -->

            <div class="item--card-content">
                <% @items.last(4).each do |item| %>
                    <div class="col-xs-3" style="padding-right: 0px; padding-left: 0px;">
                        <%= link_to item_path(item.id) ,style: "color: black;", data: {"turbolinks" => false} do %>
                        	 <%= image_tag item.image, size: "50x50" %>
                            <%#= attachment_image_tag item, :image_id, :fill, 180, 125, format: 'jpeg',fallback: "no_image.jpg" %><br>
                            <%= item.name %><br>
   
                        <% end %>
                    </div>
                <% end %>
            <div>
        </div>

        
    </div>
    <h3><%= link_to "もっと見る", items_path, class: "pull-right", style: "font-family: HiraMinPro-W6; color: #000000; margin: 30px 0;" %></h3>
</div>