config/routes.rb
Rails.application.routes.draw do
   devise_for :customers, controllers: {
   sessions:      'customers/sessions',
   passwords:     'customers/passwords',
   registrations: 'customers/registrations'
  }
namespace :customers do

          resources :bookmarks, only: [:index, :create, :update, :destroy]
end
  scope module: 'customers' do
    root 'items#top'
    resources :items, only: [:show, :index]
    get 'about' => 'items#about'

      resources :bookmarks, only: [:index, :create, :update, :destroy]
       resources :customers, only: [:show, :edit, :update] do
       #get :cart_items, on: :collection
       resources :customers, only: [:show] do 
           
           resources :items, only: %i[index new create show edit destroy update], shallow: true do
  get :bookmarks, on: :collection
  resource :bookmarks, only: %i[create destroy]
end
  end
   end
   end
   
 
   

   resources :bookmarks, only: [:create, :destroy]
 

  namespace :customers do
      resources :items, only: [:new, :create, :index, :show, :destroy] do
          
  
    resources :post_comments, only: [:create, :destroy] do
      resource :favorites, only: [:create, :destroy]
    end
  end
   
   resources :genres, only: [:show]
   patch 'customers/withdraw' => 'customers#withdraw', as: 'customers_withdraw'
 
   get 'customers/edit' => 'customers#edit'
   patch 'update' => 'customers#update'
   get 'quit' => 'customers#quit'
   get 'orders/about' => 'orders#about', as: 'orders_about'
   get 'orders/complete' => 'orders#complete'
   resources :orders, only: [:create, :new, :index, :show]
   resources :bookmarks, only: [:index, :create, :update, :destroy]

 
  end

  # adminルーティング
  devise_for :admins, controllers: {
   sessions:      'admins/sessions',
   passwords:     'admins/passwords',
   registrations: 'admins/registrations'
  }

  namespace :admins do
   root :to => 'top#top'
   resources :customers, only: [:index, :edit, :update, :show]
   resources :genres, only: [:index, :create, :edit, :update]
   resources :items, only: [:show, :index, :new, :create, :edit, :update]
   resources :orders, only: [:index, :show, :update]
   resources :order_details, only: [:update]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  has_one_attached :image
  validates :customer_id, uniqueness: { scope: :item_id }
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  validates_uniqueness_of :item_id, scope: :customer_id
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         has_many :cart_items, dependent: :destroy
         has_many :orders, dependent: :destroy
         has_many :shipping_addresses, dependent: :destroy
         has_many :post_comments, dependent: :destroy
         has_many :favorites, dependent: :destroy
         has_many :items, dependent: :destroy
         has_many :bookmarks, dependent: :destroy
         has_many :bookmark_items, through: :bookmarks, source: :item

 def bookmark(item)
  bookmark_items << item
 end

 def unbookmark(item)
  bookmark_items.destroy(item)
 end

 def bookmark?(item)
  bookmark_items.include?(item)
 end

    # 退会機能
 def active_for_authentication?
      super && (self.is_customer_status == false)
 end

 validates :last_name, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :customer
    belongs_to :post_comment
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items

  validates :name, {presence: true}
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  belongs_to :user, optional: true
  
  has_many :order_details
  has_one_attached :image
   has_many :post_comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_items, through: :bookmarks, source: :item
  
  def bookmark_by?(customer)
      bookmarks.where(customer_id: customer.id).exists?
  end

  #attachment :image
  validates :name, {presence: true}
  validates :description, {presence: true}
  
 def self.ransackable_attributes(auth_object = nil)
    ["name"]
 end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum order_status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

    enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :customer
    belongs_to :item
    
    has_many :favorites, dependent: :destroy
    def favorited_by?(customer)
        favorites.exists?(customer_id: customer.id)
    end
    
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
    belongs_to :customer

  validates :postal_code, length: {is: 7}, numericality: { only_integer: true }, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def shipping_address_for_view
  	self.postal_code + "　" + self.address + "　" + self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
        when Admin
          admins_root_path
        when Customer
          root_path
      end
    end





    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])
    end
end

app/helpers/admins/genres_helper.rb
module Admins::GenresHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/top_helper.rb
module Admins::TopHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
    <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
  <div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
        <div class="container">
          <div class="small text-center text-muted" style="margin: 50px 0;">Copyright © 2023
          </div>
        </div>
</footer>

app/views/layouts/_header.html.erb
<header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Comics</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
              <script src="https://kit.fontawesome.com/08c0548ff0.js" crossorigin="anonymous"></script>
          <li>
          
              
                      </li>
        <% if customer_signed_in? %>

          <!--カスタマーがログインしている時 -->
          <li>
           <font color="white">ようこそ、<%= current_customer.last_name %>さん！</font>
          </li>
          <li
            <i class="fa-solid fa-user" style="color: #eeff05;"></i>
            <%= link_to "マイページ", customer_path(current_customer.id) %>
          </li>
  
          <li>
            <i class="fas fa-book-open" style="color: #fcff42;"></i>
            <%= link_to "書籍一覧", items_path %>
            </li>
  
          <li>
            <i class="fas fa-star" style="color: #fbff1a;"></i>
            <%= link_to "お気に入り",  customers_bookmarks_path %>
            </li>
 
          <li>
            <i class="fas fa-question-circle" style="color: #fcff42;"></i>
            <%= link_to "About", about_path %>
            </li>
  
          <li>
            <i class="fas fa-sign-out-alt" style="color: #f1ff2e;"></i>
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
            </li>

        <% elsif admin_signed_in? %>

          <!-- 管理者がログインしている時 -->
          <li>
          <i class="fas fa-book-open" style="color: #fcff42;"></i>
            <%= link_to "書籍一覧", admins_items_path %>
            </li>
   
          <li>
            <i class="fas fa-user-friends" style="color: #f1ff29;"></i>
            <%= link_to "会員一覧", admins_customers_path %>
            </li>
     
          <li>
            <i class="fas fa-th" style="color: #f4f830;"></i>
            <%= link_to "ジャンル一覧", admins_genres_path %>
            </li>
 
          <li>
            <i class="fas fa-question-circle" style="color: #fcff42;"></i>
            <%= link_to "About", about_path %>
            </li>
   
          <li>
            <i class="fas fa-sign-out-alt" style="color: #f1ff2e;"></i>
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
            </li>

        <% else %>

          <!-- ログインしていない時 -->
          <li>
           <i class="fas fa-book-open" style="color: #fcff42;"></i>
            <%= link_to "書籍一覧", items_path %>
            </li>
    
          <li>
           <i class="fas fa-user-plus" style="color: #fbff24;"></i>
            <%= link_to "新規登録", new_customer_registration_path %>
            </li>
    
          <li>
            <i class="fas fa-question-circle" style="color: #fcff42;"></i>
            <%= link_to "About", about_path %>
            </li>
      
          <li>
            <i class="fas fa-sign-out-alt" style="color: #f1ff2e;"></i>
            <%= link_to "ログイン", new_customer_session_path %>
            </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Comics</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/08c0548ff0.js" crossorigin="anonymous"></script>
  </head>


  <% if customer_signed_in? %>
    <body id="wrapper" style="background-color: white; font-family: HiraMinPro-W6; color: #000000;">
    <!-- ヘッダー -->
    <div id="header">
      <%= render "layouts/header" %>
    </div>

    <!-- Body部分 -->
    <div class="container" style="margin-top: 20px;">
      <%= yield %>
    </div>

    <!-- Footer -->
    <%= render "layouts/footer" %>
    </body>
  <% elsif admin_signed_in? %>
    <body id="wrapper" style="background-color: #EEEEEE; font-family: HiraMinPro-W6; color: #000000;">
    <!-- ヘッダー -->
    <div id="header">
      <%= render "layouts/header" %>
    </div>

    <!-- Body部分 -->
    <div class="container" style="margin-top: 20px;">
      <%= yield %>
    </div>

    <!-- Footer -->
    <%= render "layouts/footer" %>
    </body>
  <% else %>
    <body id="wrapper" style="background-color: white; font-family: HiraMinPro-W6; color: #000000; ">
    <!-- ヘッダー -->
    <div id="header">
      <%= render "layouts/header" %>
    </div>

    <!-- Body部分 -->
    <div class="container" style="margin-top: 20px;">
      <%= yield %>
    </div>

    <!-- Footer -->
    <%= render "layouts/footer" %>
    </body>
  <% end %>
</html>